name: 'fakahani_dashboard'
version: '1.0.0+1'
publish_to: none
environment:
  sdk: '^3.6.1'
description: A new Flutter project.
dependencies:
  cupertino_icons: '^1.0.8'
  flutter:
    sdk: flutter
  flutter_gen: '^5.8.0'
dev_dependencies:
  build_runner: '^2.4.14'
  custom_lint: '^0.7.0'
  custom_lint_builder: '^0.7.0'
  flutter_gen_runner: '^5.8.0'
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: '^1.0.5'
flutter:
  uses-material-design: true
flutter_assets:
  assets_path: assets/images/
  output_path: lib/Core/helpers/utils
  filename: 'image_assets.dart'
  field_prefix: null
