name: 'fakahani_dashboard'
version: '1.0.0+1'
publish_to: none
environment:
  sdk: '^3.6.1'
description: Fakahani Dashboard.
dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  rename: ^3.0.2
  skeletonizer: ^1.4.3
dev_dependencies:
  build_runner: '^2.4.14'
  custom_lint: '^0.7.0'
  custom_lint_builder: '^0.7.0'
  flutter_gen_runner: '^5.8.0'
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: '^1.0.5'
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
flutter_assets:
  assets_path: assets/images/
  output_path: lib/Core/helpers/utils
  filename: 'image_assets.dart'
  field_prefix: null
flutter_intl:
  enabled: true
