// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfFTcQnI183nLjJ4La0qf7rWCBGgQYE9I',
    appId: '1:993626480061:web:794aeb1026ab08250d06d4',
    messagingSenderId: '993626480061',
    projectId: 'fakahani-73130',
    authDomain: 'fakahani-73130.firebaseapp.com',
    storageBucket: 'fakahani-73130.firebasestorage.app',
    measurementId: 'G-SERR75VBQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ap6wSV__8BYaRWHZGDaNPUygHkR-hgY',
    appId: '1:993626480061:android:026f34ffeed720da0d06d4',
    messagingSenderId: '993626480061',
    projectId: 'fakahani-73130',
    storageBucket: 'fakahani-73130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fZHsfh5lgE8LtgVJe04b2w93zUgA9sg',
    appId: '1:993626480061:ios:03d7e9df912ec6960d06d4',
    messagingSenderId: '993626480061',
    projectId: 'fakahani-73130',
    storageBucket: 'fakahani-73130.firebasestorage.app',
    androidClientId: '993626480061-4d77v771203tutcjldrb4vbmvjk13h3t.apps.googleusercontent.com',
    iosClientId: '993626480061-kj66ftqrh95scrblt7qejejsuqf0h4uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakahaniDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0fZHsfh5lgE8LtgVJe04b2w93zUgA9sg',
    appId: '1:993626480061:ios:03d7e9df912ec6960d06d4',
    messagingSenderId: '993626480061',
    projectId: 'fakahani-73130',
    storageBucket: 'fakahani-73130.firebasestorage.app',
    androidClientId: '993626480061-4d77v771203tutcjldrb4vbmvjk13h3t.apps.googleusercontent.com',
    iosClientId: '993626480061-kj66ftqrh95scrblt7qejejsuqf0h4uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakahaniDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfFTcQnI183nLjJ4La0qf7rWCBGgQYE9I',
    appId: '1:993626480061:web:8778887673f832660d06d4',
    messagingSenderId: '993626480061',
    projectId: 'fakahani-73130',
    authDomain: 'fakahani-73130.firebaseapp.com',
    storageBucket: 'fakahani-73130.firebasestorage.app',
    measurementId: 'G-BSRGYPJZP3',
  );

}